### ISSUE TITLE
Promote featured Actors in Actor selection

### ISSUE THREAD

**Issue by drobnikj** [apify/apify-zapier-integration#12]
Loads featured actor from Apify Store to actor run dropdown.

It is useful for Zapier users, who want to test Apify and don't have any actor yet.

**Comment by fnesveda** [comment]
This would first need an API to get the featured actors (or all public actors in the store at least).

**Comment by drobnikj** [comment]
Notes from sync
Add public Actors into the Run Actor dropdown
* The first show Actors users have
* then list Actors from the store and show them in the same order as on https://apify.com/store
* if it is possible catch the search user fill into Actors dropdown - use it to search in Actors in store
