### ISSUE TITLE
Zapier: Generate zap input based on input schema

### ISSUE THREAD

**Issue by drobnikj** [apify/apify-zapier-integration#30]
There is a feature request from the Zapier team:

```
Hi there, Apify Team!

Breetel here, reaching out from Zapier Support. One or more of our mutual customers has been having trouble setting up Zaps using the "Run Actor" action because they're not sure what to put in the field for Input Body. Many Zapier users are not familiar with json and would do not know how to format their data in this way.

We'd love to see any action steps that require json to be reconfigured so that the user would just need to input values, then your code could format those values as your API expects to receive them.

Would this be possible? Please let us know your thoughts and how we can help!
```

The problem can be solved by fetching input schema in process of Zap creation and generate fields based on it.
The Zapier allow [dynamic fields](https://zapier.github.io/zapier-platform/#customdynamic-fields), which is feature we can use.

**Comment by fnesveda** [comment]
Let's take a look how hard would it be to transform the actor input schema into the Zapier fields, I am a bit afraid it will be complicated to transform all the input schema complexity, but at least for the simple field types it could work.
