### ISSUE TITLE
Add separate zaps for Website Content Crawler, GPT Scraper

### ISSUE THREAD

**Issue by fnesveda** [apify/apify-zapier-integration#42]
This will give us better discoverability in Zapier search, right now we don't show up under "scrape" or "crawl" keywords at all.

TBD:
- should we include Web Scraper as well?
- Zapier has max 30 seconds wait time for actions, that might be painful

**Comment by fnesveda** [comment]
We might need to instruct users to split their workflows into 2 Zaps - one for scraping data and one for processing it, and one Zap would trigger the other.

TBD: Can Zaps create triggers dynamically?

**Comment by fnesveda** [comment]
Maybe the Zap name could not be based on the Actor name at all, but "Scrape single URL", "Crawl website" etc. (with "by Apify" suffix)

**Comment by drobnikj** [comment]
@mtrunkat I think this idea came from you initially.

Which options do you think are better to create action for?

1. Create action for specific Actors (Website Content Crawler, GPT Scraper, maybe Web Scraper). The action will have same input as you run Actor in Zap right now (UI generated based on input)

2. Create a specific action to "Scraper single URL" instead. We will create a nice interface where the user just fills URL and and which browser to use from the list and use Website Content Crawler under the hood with max crawled pages set up to 1.

**Comment by drobnikj** [comment]
I would more for 2, because
* can powered LLM flow just get content of one page in markdown
* good acquisition channel, if the user need a more complex scraper, can dig deep into apify
* if there is just on URL it more likely finish in 30s timeout

**Comment by mtrunkat** [comment]
(2) also makes sense to me. 

The sad thing is that this won't help us with visibility as by searching "Scrape," you won't find Apify as the search is based purely on app name, not zap name:

<img width="1393" alt="CleanShot 2023-09-22 at 11 04 39@2x" src="https://github.com/apify/apify-zapier-integration/assets/594801/5544d343-00d8-4a3c-aa3d-6fda81994dcb">

but still might be worth giving it a shot IMHO if not too much of work.

**Comment by fnesveda** [comment]
Closing as done.
